language: julia
os:
  - linux
  - windows
julia:
  - 1.4
  - 1.5
  - nightly
matrix:
  allow_failures:
    - os: windows
    - julia: 1.5
    - julia: nightly
notifications:
  email: false
after_success:
  - julia -e 'import Pkg; cd(Pkg.dir("BioMotifInference")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
